### ISSUE TITLE
update to latest game version?

### ISSUE THREAD

**Issue by PaloAlo** [karkkant/valheim-reliable_block#1]
hi, it seems to be causing issues in a dedicated server environment. players that have the mod installed cannot connect to the server.

it might need to be rebuilt with the latest game version.

**Comment by karkkant** [comment]
There doesn't seem to be any conflicts with current game version. I tested it on my local dedicated server and it worked fine. 

Do you have any more spesific error messages?

Only thing that comes to my mind is that you have some sort of anti-cheat enabled on your server that restricts client side modded clients from joining (not even sure if such tools exists tbh).

**Comment by PaloAlo** [comment]
hi, sorry for the confusion. it turns out its not your mod. everything is working well with yours. you can close this.
